#!/bin/bash

cd step0refc
FILES="refc_*.grib"

for i in $FILES; do
        if compgen -G "../step1/ens_${i%.grib}_*" > /dev/null || compgen -G "step3/EU_ens_${i%.grib}_*" > /dev/null; then
		echo "file exists in some form"
	else
                echo "splitting ${i} into the ensemble members..."
                cdo splitsel,860 ${i} "../step1/ens_${i%.grib}_"
        fi
done
